In [178]:
import pandas
import numpy as np




In [188]:
# Inicializando as matrizes com os valores do sistema 

# entrada dos valores

#             x1 x2 x3               x1 x2 x3           x1 x2 x3
A = np.array([[5.0, 1.0, 1.0],[3.0,4.0,1.0],[3.0, 3.0, 6.0]])

# vrasultados da soma   x1+x2+x3 =
b = np.array([5.0,6.0,0])

# assumindo que X = 0

x0 = np.array([0, 0, 0])


# numero de interacoes 

num_inter = 15


In [189]:
print("coeficiente da matriz:\n", A)
print("constante do vetor:\n", b)



coeficiente da matriz:
 [[5. 1. 1.]
 [3. 4. 1.]
 [3. 3. 6.]]
constante do vetor:
 [5. 6. 0.]


In [193]:
n = len(A)

x = x0.copy().astype(float)
A = A.astype(float)
b = b.astype(float)
for k in range(num_inter):
    x_old = x.copy()
    
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += A[i][j] * x_old[j]
        x[i] = (b[i] - s) / A[i][i]
    

    print("Iteration", k+1, ":", [round(num, 8) for num in x])


print(f' Resultado: X1 = {x[0]} , X2 = {x[1]} , X3 = {x[2]} \n numero de interações realisadas : {k+1} ')


Iteration 1 : [1.0, 1.5, 0.0]
Iteration 2 : [0.7, 0.75, -1.25]
Iteration 3 : [1.1, 1.2875, -0.725]
Iteration 4 : [0.8875, 0.85625, -1.19375]
Iteration 5 : [1.0675, 1.1328125, -0.871875]
Iteration 6 : [0.9478125, 0.91734375, -1.10015625]
Iteration 7 : [1.0365625, 1.06417969, -0.93257812]
Iteration 8 : [0.97367969, 0.95572266, -1.05037109]
Iteration 9 : [1.01892969, 1.03233301, -0.96470117]
Iteration 10 : [0.98647363, 0.97697803, -1.02563135]
Iteration 11 : [1.00973066, 1.01655261, -0.98172583]
Iteration 12 : [0.99303464, 0.98813346, -1.01314164]
Iteration 13 : [1.00500164, 1.00850943, -0.99058405]
Iteration 14 : [0.99641492, 0.99389479, -1.00675553]
Iteration 15 : [1.00257215, 1.00437769, -0.99515486]
 Resultado: X1 = 1.0025721490478516 , X2 = 1.0043776891326905 , X3 = -0.9951548554992676 
 numero de interações realisadas : 15 
